version: '3.8'

services:
  backend:
    build:
      context: ./Backend/Weather-Repoter
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/wr-app
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
