name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/weather-reporter-backend:latest
      FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/weather-reporter-frontend:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 🐳 Build and Push Backend Docker image
    - name: Build Backend Docker image
      run: docker build -t $BACKEND_IMAGE ./Backend/Weather-Repoter

    - name: Push Backend Docker image
      run: docker push $BACKEND_IMAGE

    # 🐳 Build and Push Frontend Docker image
    - name: Build Frontend Docker image
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_API_BASE_URL=https://api.example.com \
          -t $FRONTEND_IMAGE ./Frontend/wr-app

    - name: Push Frontend Docker image
      run: docker push $FRONTEND_IMAGE
